name: Deploy React Native App

on:
  push:
    branches: [ main ]

jobs:
  # Job de Test
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'  # Spécifiez la version de Node.js

    - name: Install Dependencies
      run: npm install

    - name: Run React Native tests
      run: npm test  # Exécute les tests React Native

  # Job de Build (Génération APK)
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'  # Spécifiez la version de Java

    - name: Install Dependencies
      run: npm install

    - name: Build APK
      run: cd android && ./gradlew assembleRelease  # Commande pour construire l'APK

  # Job de Déploiement
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Upload APK to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "android/app/build/outputs/apk/release/"  # Chemin du fichier APK
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.SSH_USER }}
        REMOTE_PORT: "22"
        TARGET: "~/path/to/destination"  # Chemin de destination sur le serveur distant
