name: Deploy React Native App

on:
  push:
    branches:
      - main

jobs:
  # Job de Build (Génération APK)
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Dependencies
      run: npm install

    - name: Build APK
      run: cd android && ./gradlew assembleRelease  # Commande pour construire l'APK

    - name: Archive APK Artifact
      uses: actions/upload-artifact@v2
      with:
        name: apk-artifact
        path: android/app/build/outputs/apk/release/

  # Job de Déploiement
  deploy:
    needs: build  # Ce job dépend du succès du job 'build'.
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - name: Download APK Artifact
      uses: actions/download-artifact@v2
      with:
        name: apk-artifact
        path: ./apk
    - name: Deploy using scp with generated RSA private key
      run: |
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ./apk/* ${{ secrets.SSH_USER }}@${{ secrets.HOST }}:~/web/app/
